ProjektZPP/Models/EfektKsztalcenia.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjektZPP.Models
{
    
    public class EfektKsztalcenia
    {
        public int Id{ get; set; }
        [Required]
        public string Nazwa { get; set; }
        [Required]
        public string Opis { get; set; }
      
        public Grupa grupa { get; set; }
    }

}

ProjektZPP/Models/Grupa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjektZPP.Models
{
    public enum Grupa
    {
        Wiedza,
        [Display(Name = "Umiejętności")]
        Umiejetnosci,
        [Display(Name = "Kompetencje Społeczne")]
        Kompetencje_społeczne

    }
}

ProjektZPP/Models/GrupaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjektZPP.Models
{
    public enum GrupaViewModel
    {
        Wiedza,
        [Display(Name = "Umiejętności")]
        Umiejetnosci,
        [Display(Name = "Kompetencje Społeczne")]
        Kompetencje_społeczne

    }
}

ProjektZPP/Models/IEfektRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjektZPP.Models
{
    public interface IEfektRepository
    {
        IEnumerable<EfektKsztalcenia> EfektyKsztalcenia { get; }
    }
}

ProjektZPP/Models/KoncepcjaKształcenia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjektZPP.Models
{
    public class KoncepcjaKształcenia
    {
        public int Id { get; set; }
        public string FormaStudiów { get; set; }
        public string TytulUzyskany { get; set; }
        public string PrzyporządkowanieObszarówKształcenia { get; set; }
        public string WskazanieDziedzinNauki { get; set; }
        public string WskazanieZwiązkuMisjąUczelni { get; set; }
        public string OgólneCeleKształcenia { get; set; }
        public string OpisKompetencjiOczekiwanych { get; set; }
        public string ZasadyRekrutacji { get; set; }

        public KoncepcjaKształcenia()
        {
            WskazanieDziedzinNauki = "Dziedzina nauk (...) , dyscypliny naukowe : podstawowa dyscyplina naukowa (...), pokrewne dyscypliny naukowe – (...)";
        }
    }
}

ProjektZPP/Models/ProgramStudiow.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjektZPP.Models
{
    public class ProgramStudiow
    {
        public int LiczbaECTS { get; set; }
        public int LiczbaSem { get; set; }
        public string strukturaStud { get; set; }
        public string TechnikiTworzenia { get; set; }
        public string BezpTech { get; set; }
        public string SposobyWer { get; set; }
        public string OpisWydz { get; set; }
    }
}

ProjektZPP/Controllers/EfektKsztalceniaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjektZPP.Database;
using ProjektZPP.Models;

namespace ProjektZPP.Controllers
{
    public class EfektKsztalceniaController : Controller
    {

        // GET: EfektKsztalcenia
        public ActionResult EfektKsztalcenia()
        {
            
                using (var db = new EfDbContext())
                {

                var efekty = db.EfektyDlaPrzedmiotu.ToList();
                ViewBag.EfektyDlaPrzedmiotu = efekty
                         .Select(x => new SelectListItem
                         {
                             Value = x.Id.ToString(),
                             Text = x.Nazwa.ToString()

                         });
                    
                }
                return View();
        }
        public void save(EfektKsztalcenia efekt)
        {
            using (var db = new EfDbContext())
            {
                
                db.Efekty.Add(efekt);
                db.SaveChanges();
            }
        }
    }
}

ProjektZPP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjektZPP.Database;

namespace ProjektZPP.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            var db = new EfDbContext();
            var efekty = db.Efekty.ToList();
            return View(efekty);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ProjektZPP/Views/EfektKsztalcenia/EfektKsztalcenia.cshtml
@model ProjektZPP.Models.EfektKsztalcenia

@{
    ViewBag.Title = "View";
}

<h2>View</h2>


@using (Html.BeginForm("save", "EfektKsztalcenia", FormMethod.Post))
{
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
        <h4>EfektKsztalcenia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.grupa, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                           @Html.EnumDropDownListFor( model => model.grupa, "Wybierz grupę", new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.odniesienie, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.odniesienie, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.odniesienie, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    ViewBag.EfektyDlaPrzedmiotu
                    <div class="form-group">
                        @Html.LabelFor(model => model.EfektyKsztalceniaDlaPrzedmiotu, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("Id",new SelectList(ViewBag.EfektyDlaPrzedmiotu, "Id", "Nazwa" ))
                            @*@Html.EditorFor(model => model.odniesienie, new { htmlAttributes = new { @class = "form-control" } })*@
                           @* @Html.ValidationMessageFor(model => model.odniesienie, "", new { @class = "text-danger" })*@
                        </div>
                    </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjektZPP/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ProjektZPP/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProjektZPP/Views/Home/Index.cshtml
@model IEnumerable<ProjektZPP.Models.EfektKsztalcenia>

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<div>
    <h4>EfektKsztalcenia</h4>
    <hr />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nazwa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Opis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.odniesienie)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nazwa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Opis)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.odniesienie)
                </td>

            </tr>
        }

    </table>
</div>

ProjektZPP/Views/Home/View.cshtml
@model IEnumerable<ProjektZPP.Models.EfektKsztalcenia>

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<div>
    <h4>EfektKsztalcenia</h4>
    <hr />
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nazwa)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Opis)
                </th>
                <th>
                    Department
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nazwa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Opis)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.odniesienie)
                    </td>
                   
                </tr>
            }

        </table>
</div>

ProjektZPP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>